temple/mandir/urls.py
from django.urls import path
from .views.main_views import add_event,event_list,list_committee,list_member,add_committee,add_member
from .views.auth_views import login

urlpatterns = [
    #auth
    path("login/",login,name="login"),
    
    
    #main
    path('add_event/',add_event,name='add_event'),
    path('event_list/',event_list,name='event_list'),
    path('list_committee/',list_committee,name='list_committee'),
    path("list_member/",list_member,name='list_member'),
    path("add_committee/",add_committee,name='add_committee'),
    path("add_member/",add_member,name='add_member'),
    
]

temple/temple/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mandir/',include('mandir.urls')),
    # path("admin/",include("admin.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

temple/mandir/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


# class User(models.Model):
#     id = models.AutoField(primary_key=True)
#     name = models.CharField(max_length=255)
#     email = models.EmailField(unique=True)
#     password = models.CharField(max_length=255)
#     role = models.CharField(max_length=50)

#     def __str__(self):
#         return self.name


class Committee(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    is_current = models.BooleanField(default=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name


class CommitteeMember(models.Model):
    m_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    address = models.TextField()
    post = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    image = models.ImageField(upload_to='committee_members/')
    c_id = models.ForeignKey(Committee, on_delete=models.CASCADE,db_column='c_id')
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Content(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    content_type = models.CharField(max_length=50)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContentImage(models.Model):
    id = models.AutoField(primary_key=True)
    content_id = models.ForeignKey(Content, on_delete=models.CASCADE)
    img_path = models.ImageField(upload_to='content_images/')

    def __str__(self):
        return f"Image for Content ID: {self.content_id.id}"


class BeADonor(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    address = models.TextField()
    phone_number = models.CharField(
        max_length=10,default='9812345678',null=False,
        validators=[
            RegexValidator(
                regex=r'^\d{10}$',
                message="Phone number must be exactly 10 digits.",
                code='invalid_phone_number'
            )
        ],
    )
    email = models.EmailField(null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    donated_date = models.DateField(null=True)

    def _str_(self):
        return self.name



class AddDonor(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    address = models.TextField()
    phone_number = models.CharField(
        max_length=10,default='9812345678',null=False,
        validators=[
            RegexValidator(
                regex=r'^\d{10}$',
                message="Phone number must be exactly 10 digits.",
                code='invalid_phone_number'
            )
        ],
    )
    email = models.EmailField(null=True)
    image = models.ImageField(upload_to='donor_images/')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    donated_date = models.DateField(null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def _str_(self):
        return self.name


class ContactUs(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self):
        return self.name

class Event(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    event_date=models.DateTimeField()
    description=models.TextField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
class EventImage(models.Model):
    event = models.ForeignKey(Event, related_name="images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='events/images/')

    def __str__(self):
        return f"Image for {self.event.title}"
    
class Notice(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=150)
    subtitle=models.CharField(max_length=255)
    description=models.TextField()
    image=models.ImageField(upload_to='notice_image')
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content_id.id
    

class Blogs(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=150)
    subtitle=models.CharField(max_length=255)
    description=models.TextField()
    image=models.ImageField(upload_to='blog_image/')
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content_id.id

class mission_vision(models.Model):
    id=models.AutoField(primary_key=True)
    description=models.TextField()
    content_id=models.ForeignKey(Content,on_delete=models.CASCADE,db_column='content_id')
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content_id.id

temple/mandir/forms.py
from django import forms
from .models import Event,Committee,Blogs,CommitteeMember,Notice,mission_vision,AddDonor,EventImage
from django.contrib.auth.models import User

# class LoginForm(forms.ModelForm):
#     class Meta:
#         model=User
#         fields=["username","password"]


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'event_date', 'description']

    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True}), required=False)

    
class EventImageForm(forms.ModelForm):
    class Meta:
        model = EventImage
        fields = ['image']
        

class blogform(forms.ModelForm):
    class Meta:
        models=Blogs
        fields="__all__"
        
class committeeform(forms.ModelForm):
    class Meta:
        model= Committee
        fields=['name','start_date','end_date','is_current']
        
        

        
class memberform(forms.ModelForm):
    c_id = forms.ModelChoiceField(
        queryset=Committee.objects.all(),
        empty_label="Select Committee",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    class Meta:
        model=CommitteeMember
        fields=['name', 'address', 'position', 'image', 'c_id', 'user']

temple/mandir/views/auth_views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login as LOGIN
# from ..forms import LoginForm


def login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=authenticate(request,username=username,password=password)
        if user is not None:
            LOGIN(request,user)
            return redirect("add_event")
        else:
            return redirect("login")
    return render(request,"auth/login.html")

temple/mandir/views/main_views.py
from django.shortcuts import render,redirect,get_object_or_404 
from ..models import Event,Blogs,Committee,CommitteeMember,EventImage
from ..forms import EventForm,blogform,committeeform,memberform
from django.contrib.auth.decorators import login_required


@login_required
def add_event(request):
    if request.method == "POST":
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.save()

            for image in request.FILES.getlist('images'):#save garna
                EventImage.objects.create(event=event, image=image)

            return redirect('event_list')
    else:
        form = EventForm()
    return render(request, 'main/add_event.html', {'form': form})

def event_list(request):
    event=Event.objects.all().order_by('-created_at')
    return render(request,'main/event_list.html',{'event':event})

def edit_event(request,event_id):
    event=get_object_or_404(Event,pk=event_id,user=request.user)
    if request.method=='POST':
        form=EventForm(request.POST,request.FILES,instance=event)
        if form.is_valid():
            event=form.save(commit=False)
            event.user=request.user
            event.save()
            return redirect('event_list')
    else:
        form=EventForm(instance=event)
    return render(request,'main/edit_event.html',{'from':form})

def delete_event(request,event_id):
    event=get_object_or_404(Event,pk=event_id,user=request.user)
    if request.method=='POST':
        event.delete()
        return redirect('event_list')
    return render(request,'delete_tweet.html',{'event':event})


def list_blog(request):
    blog=Blogs.objects.all().order_by('-created_at')
    return render(request,'list_blog.html',{'blog':blog})

def add_blog(request):
    if request.method=='POST':
        form=blogform(request.POST,request.FILES)
        if form.is_valid():
            blog=form.save(commit=False)
            blog.user=request.user
            blog.save()
            return redirect("list_blog")
    else:
        form=blogform()
        
    return render(request,'add_blog.html',{'form':form})

def edit_blog(request,blog_id):
    blog=get_object_or_404(Blogs,pk=blog_id,user=request.user)
    if request.method=='POST':
        form=blogform(request.POST,request.FILES,instance=blog)
        if form.is_valid():
            blog=form.save(commit=False)
            blog.user=request.user
            blog.save()
            return redirect("list_blog")
    else:
        form=blogform(instance=blog)
        
    return render(request,'add_blog.html',{'form':form})

def delete_blog(request,blog_id):
    blog=get_object_or_404(Blogs,pk=blog_id,user=request.user)
    if request.method=='POST':
        blog.delete()
        return redirect("list_blog")
    return render(request,'delete_blog.html',{'blog':blog})

def list_committee(request):
    form=Committee.objects.all().order_by('-created_at')
    return render(request,'main/list_committee.html',{'form':form})

@login_required
def add_committee(request):
    if request.method=='POST':
        form=committeeform(request.POST)
        if form.is_valid():
            committee=form.save(commit=False)
            committee.user=request.user
            committee.save()
            return redirect('add_committee')
    else:
        form=committeeform()
    return render(request,'main/add_committee.html',{'form':form})


def edit_committee(request):
    pass

def delete_committee(request,c_id):
    pass

def list_member(request):
    form=CommitteeMember.objects.all().order_by("-c_id")
    return render(request,"main/list_member.html",{'form':form})

@login_required
def add_member(request):
    if request.method=='POST':
        form=memberform(request.POST,request.FILES)
        if form.is_valid():
            member=form.save(commit=False)
            member.user=request.user
            member.save()
            return redirect('add_member')
    else:
        form=memberform()
    return render(request,"main/add_member.html",{'form':form})

temple/mandir/templates/main/add_committee.html
{% extends 'components/_navbar.html' %}

{% block content %}

<div class="bg-white border rounded-lg px-8 py-6 mx-auto my-8 max-w-2xl">
    <h2 class="text-2xl font-medium mb-4">Add Committee</h2>
    <form method="POST" action="{% url 'add_committee' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Title Input -->
        <div class="mb-4">
            <label for="name" class="block text-gray-700 font-medium mb-2">Name</label>
            <input type="text" id="name" name="name"
                class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
        </div>
    
        <!-- Event Date Input -->
        <div class="mb-4">
            <label for="start_date" class="block text-gray-700 font-medium mb-2">Event Date</label>
            <input type="date" id="start_date" name="start_date"
                class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
        </div>
        <div class="mb-4">
            <input id="is_current" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500">
            <label for="is_current" class="w-full py-3 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Is_current</label>
        </div>
    
        <!-- Submit Button -->
        <div class="text-center">
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600">Submit</button>
        </div>
    </form>
    
    
</div>

{% endblock %}

temple/mandir/templates/main/add_event.html
{% extends 'components/_navbar.html' %}
{% block content %}

    <div class="bg-white border rounded-lg px-8 py-6 mx-auto my-8 max-w-2xl">
        <h2 class="text-2xl font-medium mb-4">Add Event</h2>
        <form method="POST" action="{% url 'add_event' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Title Input -->
            <div class="mb-4">
                <label for="title" class="block text-gray-700 font-medium mb-2">Title</label>
                <input type="text" id="title" name="title"
                    class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
            </div>
        
            <!-- Event Date Input -->
            <div class="mb-4">
                <label for="event_date" class="block text-gray-700 font-medium mb-2">Event Date</label>
                <input type="date" id="event_date" name="event_date"
                    class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
            </div>
        
            <!-- Image Upload -->
            <div class="mb-4">
                <label for="images" class="block text-gray-700 font-medium mb-2">Upload Images</label>
                <input type="file" id="images" name="images" multiple
                    class="w-full text-gray-500 font-medium text-sm bg-gray-100 file:cursor-pointer cursor-pointer file:border-0 file:py-2 file:px-4 file:mr-4 file:bg-gray-800 file:hover:bg-gray-700 file:text-white rounded" />
            </div>
        
            <!-- Description Input -->
            <div class="mb-4">
                <label for="description" class="block text-gray-700 font-medium mb-2">Event Description</label>
                <textarea name="description" id="description" cols="30" rows="10"
                    class="mb-10 h-40 w-full resize-none rounded-md border border-slate-300 p-5 font-semibold text-gray-300"></textarea>
            </div>
        
            <!-- Submit Button -->
            <div class="text-center">
                <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600">Submit</button>
            </div>
        </form>
        
        
    </div>
{% endblock %}

temple/mandir/templates/main/add_member.html
{% extends 'components/_navbar.html' %}

{% block content %}

<div class="bg-white border rounded-lg px-8 py-6 mx-auto my-8 max-w-2xl">
    <h2 class="text-2xl font-medium mb-4">Add Member</h2>
    <form method="POST" action="{% url 'add_member' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Title Input -->
        <div class="mb-4">
            <label for="name" class="block text-gray-700 font-medium mb-2">Name</label>
            <input type="text" id="name" name="name"
                class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
        </div>

        <div class="mb-4">
            <label for="address" class="block text-gray-700 font-medium mb-2">Address</label>
            <input type="text" id="address" name="address"
                class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
        </div>

        <div class="mb-4">
            <label for="position" class="block text-gray-700 font-medium mb-2">Position</label>
            <input type="text" id="position" name="position"
                class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
        </div>
    
        <!-- Event Date Input -->
        {% comment %} <div class="mb-4">
            <label for="event_date" class="block text-gray-700 font-medium mb-2">Event Date</label>
            <input type="date" id="event_date" name="event_date"
                class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
        </div> {% endcomment %}
    
        <!-- Image Upload -->
        <div class="mb-4">
            <label for="images" class="block text-gray-700 font-medium mb-2">Upload Images</label>
            <input type="file" id="images" name="images"
                class="w-full text-gray-500 font-medium text-sm bg-gray-100 file:cursor-pointer cursor-pointer file:border-0 file:py-2 file:px-4 file:mr-4 file:bg-gray-800 file:hover:bg-gray-700 file:text-white rounded" />
        </div>

        {% comment %} <div class="mb-4">
            <label for="gender" class="block text-gray-700 font-medium mb-2">Committee Year</label>
            <select id="gender" name="gender"
                class="border border-gray-400 p-2 w-full rounded-lg focus:outline-none focus:border-blue-400" required>
                <option value="">Select Committee</option>
                {% for committe in form %}
                <option>{{committe.name}}</option>
                {% endfor %}
            </select>
        </div> {% endcomment %}
        <div class="form-group">
            <label for="id_c_id">Committee:</label>
            {{ form.c_id }}
        </div>
    
    
        <!-- Submit Button -->
        <div class="text-center">
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600">Submit</button>
        </div>
    </form>
    
    
</div>

{% endblock %}

temple/mandir/templates/main/edit_committee.html
{% extends 'components/_navbar.html' %}

{% block content %}



{% endblock %}

temple/mandir/templates/main/event_list.html
{% extends 'components/_navbar.html' %}

{% block content %}

<div class="max-w-screen-xl mx-auto p-16">
    

    <div class="sm:grid lg:grid-cols-3 sm:grid-cols-2 gap-10">
        {% for events in event %}
        <div
            class="hover:bg-gray-900 hover:text-white transition duration-300 max-w-sm rounded overflow-hidden shadow-lg">
            <div class="py-4 px-8">
                <img src="https://tailwindcss.com/img/jonathan.jpg" class="rounded-full h-12 w-12 mb-4">
                <a href="#">
                    <h4 class="text-lg mb-3 font-semibold">{{events.title}}</h4>
                </a>
                <p class="mb-2 text-sm text-gray-600">L{{events.description}}

                <img src="https://images.pexels.com/photos/461077/pexels-photo-461077.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=1&amp;w=500" class="w-100">

                <hr class="mt-4">
                <span class="text-xs">ARTICLE</span>
                &nbsp;<span class="text-xs text-gray-500">PROCESS</span>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}